export const ErrorCodes = {
  VALIDATION: {
    INVALID_FORMAT: "VALIDATION:INVALID_FORMAT",
    INVALID_VALUE: "VALIDATION:INVALID_VALUE",
  },
  AUTH: {
    INSUFFICIENT_PERMISSIONS: "AUTH:INSUFFICIENT_PERMISSIONS",
    INSUFFICIENT_CREDENTIALS: "AUTH:INSUFFICIENT_CREDENTIALS",
    UNEXPECTED_ERROR: "AUTH:UNEXPECTED_ERROR",
  },
  SERVICE: {
    USERNAME_EXISTS: "SERVICE:USERNAME_EXISTS",
    EMAIL_EXISTS: "SERVICE:EMAIL_EXISTS",
    USERNAME_NOT_EXIST: "SERVICE:USERNAME_NOT_EXIST",
    EMAIL_NOT_EXIST: "SERVICE:EMAIL_NOT_EXIST",
    NOT_FOUND: "SERVICE:NOT_FOUND",
    UNEXPECTED_ERROR: "SERVICE:UNEXPECTED_ERROR",
  },
  DB: {
    USERNAME_EXISTS: "DB:USERNAME_EXISTS",
    EMAIL_EXISTS: "DB:EMAIL_EXISTS",
    ACCOUNT_EXISTS: "DB:ACCOUNT_EXISTS",
    TABLE_OR_INDEX_NOT_EXIST: "DB:TABLE_OR_INDEX_NOT_EXIST",
    UNEXPECTED_ERROR: "DB:UNEXPECTED_ERROR",
    CONNECTION_FAILED: "DB:CONNECTION_FAILED",
    VALIDATION_VALUE: "DB:VALIDATION_VALUE",
    CONDITION_CHECK_FAILIURE: "DB:CONDITION_CHECK_FAILIURE",
    NOT_FOUND: "DB:NOT_FOUND",
  },
  AWS: {
    UNEXPECTED_ERROR: "AWS:UNEXPECTED_ERROR",
    SERVICE_ERROR: "AWS:SERVICE_ERROR",
  },
};
